language: r
r:
  - bioc-release
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/R/Library

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

dist: xenial

sudo: required

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.6
      - python3.6-dev
      - libgit2-dev
      - libhdf5-dev
      - libtool
      - texinfo

env:
  global:
    - PYTHON=python3.6

before_install:
  - $PYTHON --version
  - curl https://bootstrap.pypa.io/get-pip.py | sudo -H $PYTHON
  - sudo $PYTHON -m pip install --upgrade pip
  - pip install --user numpy keras h5py six scikit-learn scanpy kopt pandas
  - pip install --user dca
  - pip install --user magic-impute
  - pip install --user git+https://github.com/milescsmith/AutoImpute.git

install:
- R -e 'devtools::install_deps(dep = T)'

script:
- R CMD build .
- R CMD check *tar.gz
